- name: print msg 
  hosts: all
  become: true
  tasks:
    - name: Gather Facts 
      debug:
        msg: "Hello World"
    - name: print os 
      debug:
        msg: "{{ansible_os_family}}"
    - name: print error 
      debug:
        msg: "{{abc.123}}"
    - name: print os 
      debug:
        msg: "{{ansible_processor_cores}}"

