- name: print msg 
  hosts: all
  become: true
  tasks:
    - name: Gather Facts #gather facts
      debug:
        msg: "Hello World"
    - name: print os 
      debug:
        msg: "{{ansible_os_family}}"   #print facts
    - name: print error 
      debug:
        msg: "{{abc.123}}"
      ignore_errors: true          #ignore errors
    - name: print os 
      debug:
        msg: "{{ansible_processor_cores}}"
    # - name: Task 1 (conditional)
    #   command:  yum install java -y
    #   when: ansible_os_family == "Debian" or ansible_os_family == "Redhat"
    - name: Task 1 (conditional)
      command:  yum install java -y
      when: ansible_os_family == "RedHat"