- name: install and configure mariadb
  hosts: db_servers
  become: true
  tasks:
    - name: install mariadb
      package:
        name: mariadb105-server
        state: present

    - name: Start MariaDB
      service:
        name: mariadb
        state: started
        enabled: yes

    - name: install pip module
      pip:
        name:
          - pexpect
        state: present

    - name: Is root password set?
      command: mysql -u root --execute "SELECT NOW()"
      register: is_root_password_set
      ignore_errors: yes

    - name: secure mariadb
      expect:
        command: mysql_secure_installation
        responses:
          'Enter current password for root': ''
          'Set root password': 'y'
          'New password': '12345'
          'Re-enter new password': '12345'
          'Remove anonymous users': 'y'
          'Disallow root login remotely': 'n'
          'Remove test database': 'y'
          'Reload privilege tables now': 'y'
      register: secure_mariadb
      failed_when: "'... Failed!' in secure_mariadb.stdout"
      become: true

    - name: create user mariadb
      hosts: db_servers
      become: true
      tasks:
        - name: Run command 1
          command: sudo -i 
        - name: Run command 2
          command: mysql -u root -p12345 -e "CREATE USER 'deepak'@'localhost' IDENTIFIED BY '12345';"
        - name: Run command 3
          command: mysql -u root -p12345 -e "GRANT ALL PRIVILEGES ON *.* TO 'deepak'@'localhost';"
        - name: Run command 4
          command: mysql -u root -p12345 -e "FLUSH PRIVILEGES;"
        - name: Run command 5
          command: exit;
